services:
  # A web service
  - type: web
    name: deepfake-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: DOWNLOAD_MODELS
        value: true
      - key: DEVICE
        value: cpu
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
